version: '3.4'

services:
  
  senderapi:
    image: ${ACR_NAME}.azurecr.io/senderapi:dev
    environment:
      - SERVICE_BUS_STRING=${SERVICE_BUS_STRING}}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "10000:5000"
      - "10001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    build:
      context: .
      dockerfile: SenderAPI/Dockerfile

  receiverapi:
    image: ${ACR_NAME}.azurecr.io/receiverapi:dev
    environment:
      - SERVICE_BUS_STRING=${SERVICE_BUS_STRING}}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=6000
      - ASPNETCORE_HTTPS_PORTS=6001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    ports:
      - "20000:6000"
      - "20001:6001"
    build:
      context: .
      dockerfile: ReceiverAPI/Dockerfile
