version: '3.4'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 3

  senderapi:
    image: ${ACR_NAME}.azurecr.io/senderapi:dev
    environment:
      - ACR_NAME=${ACR_NAME}
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "10000:5000"
      - "10001:5001"
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: SenderAPI/Dockerfile

  receiverapi:
    image: ${ACR_NAME}.azurecr.io/receiverapi:dev
    environment:
      - ACR_NAME=${ACR_NAME}
      - ASPNETCORE_HTTP_PORTS=6000
      - ASPNETCORE_HTTPS_PORTS=6001
    ports:
      - "20000:6000"
      - "20001:6001"
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: ReceiverAPI/Dockerfile
