name: Build and deploy multiple containers to an Azure Web App

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  ACR_NAME: ${{ secrets.ACR_NAME }}

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_ADMIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push SenderAPI image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/senderapi:dev
          file: ./SenderAPI/Dockerfile

      - name: Build and push ReceiverAPI image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/receiverapi:dev
          file: ./ReceiverAPI/Dockerfile

      - name: Upload docker-compose.yml as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-file
          path: ./docker-compose.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Download docker-compose.yml artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-compose-file

      - name: Set ACR_NAME Environment Variable
        run: echo "ACR_NAME=${{ env.ACR_NAME }}" >> $GITHUB_ENV

      - name: Replace variables in docker-compose.yml
        run: |
          envsubst < ${{ github.workspace }}/docker-compose.yml > ${{ github.workspace }}/docker-compose.yml.new
          mv ${{ github.workspace }}/docker-compose.yml.new ${{ github.workspace }}/docker-compose.yml

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: |
            ${{ env.ACR_NAME }}.azurecr.io/senderapi:dev
            ${{ env.ACR_NAME }}.azurecr.io/receiverapi:dev
          configuration-file: ${{ github.workspace }}/docker-compose.yml

